<a href="https://colab.research.google.com/github/Putt2020/pytorch_beginner/blob/main/torch_math_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [14]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([1,3,5,7])
c = torch.tensor([1,1,1,1])
print(a, b, c)

tensor([1, 2, 3, 4]) tensor([1, 3, 5, 7]) tensor([1, 1, 1, 1])


In [13]:
print(a + b)
print(torch.add(a, b))
print(a.add(b))

tensor([ 2,  5,  8, 11])
tensor([ 2,  5,  8, 11])
tensor([ 2,  5,  8, 11])


In [7]:
print(a - b)
print(torch.sub(a, b))

tensor([ 0, -1, -2, -3])
tensor([ 0, -1, -2, -3])


In [8]:
print(a * b)
print(torch.mul(a, b))

tensor([ 1,  6, 15, 28])
tensor([ 1,  6, 15, 28])


In [9]:
print(a / b)
print(torch.div(a, b))

tensor([1.0000, 0.6667, 0.6000, 0.5714])
tensor([1.0000, 0.6667, 0.6000, 0.5714])


In [11]:
print(a % b)
print(torch.remainder(a, b))

tensor([0, 2, 3, 4])
tensor([0, 2, 3, 4])


In [12]:
print(torch.pow(a, b))

tensor([    1,     8,   243, 16384])


In [ ]:
#Reassignment
c.add_(b)
print(c)